### PR TITLE
Fix a typo in the README.md

### PR DESCRIPTION
**Pull request by stcheng**
Replace '最' with '坠'

### CODE REVIEW

**Comment by fakefred** [comment]
Two popular combinations exist: 最好 and 坠吼. Please completely fix.

**Comment by fakefred** [comment]
As a big-news event for the hath, I approve this pull request. Status is still pending, since @hczhcz is owner of this repo and is in duty of commits. 

`~~~~happy ha'ing!~~~~`

**Comment by hczhcz** [comment]
Thanks for the PR!
It was intentionally written in the original style of the quotes. See [Wikiquote](https://zh.wikiquote.org/zh-hans/%E6%B1%9F%E6%B3%BD%E6%B0%91).

**Comment by stcheng** [comment]
Thanks. Understood.

**Pull request closed without merging**
